#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Only use Commitizen when explicitly called
if [ "$2" = "commit" ] && [ -z "${GIT_COMMIT_MESSAGE-}" ]; then
  exec < /dev/tty && pnpm cz --hook || true
fi